trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TF_ROOT: azure-terraform-ado

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(TF_ROOT)'
    backendServiceArm: 'azure-oidc-sc'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(TF_ROOT)'
    environmentServiceNameAzureRM: 'azure-oidc-sc'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(TF_ROOT)'
    environmentServiceNameAzureRM: 'azure-oidc-sc'
    commandOptions: '-auto-approve'
